config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :flats, only: [:index, :show] do
    resources :reviews, only: [:show, :create]
    resources :bookings, only: [:new , :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat
end

app/models/flat.rb
class Flat < ApplicationRecord
  # skip_before_action :authenticate_user!, only: :home
  has_many :reviews, dependent: :destroy
  has_many :reviewed_users, through: :reviews, source: :user

  has_many :bookings, dependent: :destroy
  has_many :visitors, through: :bookings, source: :user

  belongs_to :host, class_name: "User"

  has_many :users

  validate :host_role

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  private

  def host_role
    p "host"
    p host
    p self.host
    if host.role != "host"
      errors.add(:host, 'Users without host role cannot be the host of a flat')
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :flat
  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews
  has_many :reviewed_flats, through: :reviews, source: :flat

  has_many :bookings
  has_many :booked_flats, through: :bookings, source: :flat

  has_many :flats, foreign_key: "host_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new
    if params[:check_in].present? && params[:check_out].present?
      @check_in = params[:check_in]
      @check_out = params[:check_out]
    else
      @check_in = Date.today.strftime("%Y-%m-%d")
      @check_out = (Date.today + 3).strftime("%Y-%m-%d")
    end
  end

  def create
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new(booking_params)
    @booking.flat = @flat
    @booking.user = current_user
    if @booking.save
       # session[:price] = @flat.price * (@booking.end_date - @booking.start_date + 1)
       # session[:check_in] = @booking.start_date
       # session[:check_out] = @booking.end_date
       # session[:flat_name] = @flat.title
       redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
    @check_in = Date.today.strftime("%Y-%m-%d")
    @check_out = (Date.today + 3).strftime("%Y-%m-%d")

    if search_params.present?
      @location = search_params["location"]
      @check_in = search_params["check_in"]
      @check_out = search_params["check_out"]
      if search_params["capacity"].present?
        @capacity = search_params["capacity"].to_i
        @flats = Flat.where("location ILIKE ? AND capacity = ?", @location, @capacity)
      else
        @flats = Flat.where("location ILIKE ?", @location)
      end
    end

     @markers = @flats.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { flat: flat }),
        image_url: helpers.asset_url('marker.png')
      }
    end
  end

  def show
    @flat = Flat.find(params[:id])
    @review = Review.new
    if params[:check_in].present? && params[:check_out].present?
      @check_in = params[:check_in]
      @check_out = params[:check_out]
    else
      @check_in = Date.today.strftime("%Y-%m-%d")
      @check_out = (Date.today + 3).strftime("%Y-%m-%d")
    end
  end

  private

  def search_params
    params.require(:search).permit(:location, :capacity, :check_in, :check_out)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @flat = Flat.find(params[:flat_id])
    @review = Review.new(review_params)
    @review.flat = @flat
    @review.user_id = current_user.id
    if @review.save
      redirect_to flat_path(@flat, anchor: "anchor")
    else
      redirect_to flat_path(@flat)
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class= "card-booking">
  <div class="container">
    <div class="row">
      <div class="col-4">
      </div>
      <div class="col-4">
        <div class="card" id="card-booking">
          <div class="justify-content-center">
            <%= simple_form_for [@flat, @booking ] do |f| %>
              <h4>Start Date</h4>
              <%= f.input :start_date, as: :date, html5: true, label: false, input_html: { value: @check_in } %>
              <h4>End Date </h4>
              <%= f.input :end_date, as: :date, html5: true, label: false, input_html: { value: @check_out } %>
              <%= f.submit "Book now", class: "btn btn-outline-success w-100" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/_infowindow.html.erb
<h4><%= flat.title %></h4>
<p>Adress: <%= flat.address %></p>
<p>Price: <strong><%= flat.price %>€</strong></p>

app/views/flats/index.html.erb
<div class ="container-fluid">

    <div class="filters">
      <button type="button" id="price-filter" class="btn btn-outline-secondary">Price</button>
      <button type="button" id="type-filter" class="btn btn-outline-secondary">Type</button>
    </div>

    <div class="card text-center" id="price-card" style="display: none">
      <div class="card-body">
        <h5 class="card-title">The average price per night is 55€</h5>

        <div class="dual-input">
          <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Minimum price" id="minimum-price">
          </div>

          <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Maximum price" id="maximum-price">
          </div>
        </div>

        <button type="button" id="save-price" class="btn btn-dark">Save</button>
      </div>
    </div>

    <div class="card text-center" id="type-card" style="display: none">

      <br>


      <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
          <label class="form-check-label" for="defaultCheck1" id="defaultText1">full accommodation</label>
      </div>
      <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="defaultCheck2">
          <label class="form-check-label" for="defaultCheck2" id="defaultText2">private room</label>
      </div>
      <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="defaultCheck3">
          <label class="form-check-label" for="defaultCheck3" id="defaultText3">hotel room</label>
      </div>
      <div class="form-check">
          <input class="form-check-input" type="checkbox" value="" id="defaultCheck4">
          <label class="form-check-label" for="defaultCheck4" id="defaultText4">shared room</label>
      </div>

      <br>

      <div>
        <button type="button" id="save-type" class="btn btn-dark">Save</button>
      </div>

      <br>

    </div>

  <div class="main-container">

   <div class="cards">
      <% @flats.each do |flat| %>
   <div data-price='<%=flat.price%>' data-type='<%=flat.flat_type%>' class="flat">

    <div class="card-flat">
       <%= render 'shared/carousel', flat_id: flat.id, url1: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60", url2: "https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60", url3: "https://images.unsplash.com/photo-1484154218962-a197022b5858?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" %>

    <div class="card-top">

        <small>
          <% unless flat.reviews.empty? %>
            <% count = 0 %>
            <% 5.times do %>
            <% if flat.reviews.first.rating > count %>
              <!-- fills the star in -->
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-star-fill text-warning stars" fill="rgb(251, 130, 130)" xmlns="http://www.w3.org/2000/svg">
                <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
              </svg>
            <% else %>
              <!-- empty star -->
              <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-star" fill="rgb(251, 130, 130)" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.523-3.356c.329-.314.158-.888-.283-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767l-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288l1.847-3.658 1.846 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.564.564 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
              </svg>
            <% end %>
            <% count += 1 %>
            <% end %>
          <% end %>
        </small>

         <h5><%= flat.title %> - <%= flat.location %></h5>
      </div>
         <div class="card-bottom">
         <p> <strong>€<%=flat.price%></strong> / night</p>
         <%= link_to "Check details", flat_path(flat), class: "btn btn-success btn-sm" %>
         </div>
   </div>
 </div>
   <% end %>
   </div>
   <div id="map"
     style="width: 100%;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
   </div>

  </div>
</div>

app/views/flats/new.html.erb
<%= form_for(@flat) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <%= f.label :price %>
  <%= f.number_field :price %>
  <%= f.submit %>
<% end %>

app/views/flats/show.html.erb
<div class="container">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div class="carousel-style">
          <img class="d-block w-100 show-image" id="img1" src="https://cdn.archilovers.com/projects/57d7daff-e586-4a1b-83b3-8d5bf0f8e070.jpg" alt="First slide">
        </div>
      </div>
      <div class="carousel-item">
        <div class="carousel-style">
        <img class="d-block w-100 show-image" id="img2" src="https://roohome.com/wp-content/uploads/2016/07/modern-house-interior-design-1280x720.jpg" alt="Second slide">
        </div>
      </div>
      <div class="carousel-item">
        <div class="carousel-style">
        <img class="d-block w-100 show-image" id="img3" src="https://pix10.agoda.net/hotelImages/4408208/-1/3260e9011390a7b17674c23013cc1a1c.jpg?s=1024x768" alt="Third slide">
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon"  aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<div class="container py-3">
  <div class="row">
    <div class="col-md-8">
      <div class="title border-bottom">
        <h1><%= @flat.title%>,</h1> <h3><%=@flat.location %></h3>
      </div>
      <div class="description">
        <div class="short-description">
          <% if @flat.reviews.count != 0 %>
            <% sum = 0 %>
            <% total_reviews = @flat.reviews.count %>
              <% @flat.reviews.each do |review| %>
                <% sum += review.rating %>
              <% end %>
              <% avg = (sum / total_reviews) %>
              <% stars = avg %>
              <% stars.times do %>
                <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-star-fill text-warning stars" fill="rgb(251, 130, 130)" xmlns="http://www.w3.org/2000/svg">
                  <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                </svg>
              <%end%>
              <% if stars > 4%>
              <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-award-fill" style = "color: #1ED785" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M8 0l1.669.864 1.858.282.842 1.68 1.337 1.32L13.4 6l.306 1.854-1.337 1.32-.842 1.68-1.858.282L8 12l-1.669-.864-1.858-.282-.842-1.68-1.337-1.32L2.6 6l-.306-1.854 1.337-1.32.842-1.68L6.331.864 8 0z"/>
                <path d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z"/>
              </svg>
              <%end%>
              (<%= @flat.reviews.count %>)
          <% else %>
            <p>No rating</p>
          <% end %>
        </div>

        <% @flat.bookings.select { |booking| booking.user == current_user}.each do |booking| %>
          <div class="card-description p-3 mb-3">
            <h4> Booking was successfull! 😎🤘</h4>
            <h5> See details: </h5>
            <p> Flat: <%= @flat.title %></p>
            <p> Check in: <%= booking.start_date %></p>
            <p> Check out: <%= booking.end_date %></p>
            <p> Price: <%= (@flat.price * (booking.end_date - booking.start_date + 1)).to_i %></p>
          </div>
        <% end %>

          <div class="card-description p-3 mb-3">
            <h4> Description </h4>
            <p>A <%= @flat.flat_type %> where you can enjoy some nice leisure time or even work remotely now that you have your Le Wagon course :)</p>
          </div>

          <!-- review form -->
          <%= simple_form_for([@flat, @review], remote: true) do |f| %>
            <%= f.input :rating, collection: 0..5, label: "Leave a Rating"%>
            <%= f.input :text, label:"Leave a Review" %>
            <%= f.submit class: 'btn btn-primary' %>
          <% end %>

          <!-- list the reviews -->
          <div  id="anchor" class='list-group thin-border-top mt-5 mb-3'>
            <% if @flat.reviews.count != 0 %>
              <h3 class="mt-5" ><%= @flat.reviews.count %> Reviews</h3>
              <% @flat.reviews.reverse.each do |review| %>
                <li class="review-card list-group-item mt-3">
                  <div class="review-content mt-3">
                    <!-- Reviewer avatar -->
                    <%= image_tag "https://kitt.lewagon.com/placeholder/users/RicardoLuisAraujo", class: "review-avatar" %>
                    <!-- Reviewer name -->
                    <div class="pl-2">
                      <div>
                        <%= review.user.first_name  %>
                      </div>
                      <div>
                      <!-- Review Date -->
                       <%= Time.new.strftime("%B, %Y")%>
                      </div>
                    </div>
                  </div>

                    <!-- Review Rating -->
                    <small>
                      <% count = 0 %>
                      <% 5.times do %>
                        <% if review.rating > count %>
                        <!-- fills the star in -->
                          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-star-fill text-warning stars" fill="rgb(251, 130, 130)" xmlns="http://www.w3.org/2000/svg">
                            <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.283.95l-3.523 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                          </svg>
                        <% else %>
                        <!-- empty star -->
                          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-star" fill="rgb(251, 130, 130)" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.523-3.356c.329-.314.158-.888-.283-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767l-3.686 1.894.694-3.957a.565.565 0 0 0-.163-.505L1.71 6.745l4.052-.576a.525.525 0 0 0 .393-.288l1.847-3.658 1.846 3.658a.525.525 0 0 0 .393.288l4.052.575-2.906 2.77a.564.564 0 0 0-.163.506l.694 3.957-3.686-1.894a.503.503 0 0 0-.461 0z"/>
                          </svg>
                        <% end %>
                        <% count += 1 %>
                      <% end %>
                    </small>
                    <!-- Review text -->
                    <p><%= review.text %></p>
                </li>
              <% end %>
            <% else %>
              <h3 class="mt-3" >No Reviews</h3>
            <% end %>
          </div>
      </div>
    </div>

  <div class="col-md-4">
          <!-- checkout -->
          <div class="bg-white border p-3 sticky-top" id="confirmation-card">
              <%= link_to "Go to Booking",  new_flat_booking_path(@flat, check_in: @check_in, check_out: @check_out), class: "btn btn-outline-success w-100" %>

            <div class="d-flex justify-content-between mt-3">
              <p><strong>Nights</strong></p>
              <div class="col-sm-3 my-1">
                <select class="form-control form-control-sm" type="search">
                  <option value="">1</option>
                  <option value="">2</option>
                  <option value="">3</option>
                  <option value="">4</option>
                  <option value="">5+</option>
                </select>
              </div>
            </div>

            <div class="d-flex justify-content-between mt-3">
              <p><strong>Guests</strong></p>
              <p>??</p>
            </div>

            <div class="d-flex justify-content-between mt-3 border-bottom">
              <p><strong>Fees</strong></p>
              <p><%fees = rand(10..50) %> <%=fees%>€</p>
            </div>

            <div class="d-flex justify-content-between mt-3">
              <p><strong>Total</strong></p>
              <p><strong><%= @flat.price * rand(1..5) + fees %>€</strong></p>
            </div>
          </div>
          <!-- /checkout -->
        </div>
      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAirbnbClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Montserrat">
          <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Raleway">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <%= render 'shared/flashes' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1501927023255-9063be98970c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1267&q=80);">
  <div class="container justify-content-center text-center ">
    <h1>Find your perfect flat!</h1>
    <p>Explore your city COVID Free</p>
  </div>
</div>

<div class ="container">
  <div class="d-flex justify-content-around">
   <%= render 'shared/card', title: "Lisbon", text: "Find your beautiful flat in Lisbon", url: "https://images.unsplash.com/photo-1513377888081-794d8e958972?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" %>
   <%= render 'shared/card', title: "Porto", text: "Find your beautiful flat in Porto", url: "https://images.unsplash.com/photo-1555881400-89d5a9c86668?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" %>
   <%= render 'shared/card', title: "Prague", text: "Find your beautiful flat in Prague", url: "https://images.unsplash.com/photo-1560950340-5e6064fce41a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" %>
  </div>
</div>

<div class ="container">
  <div class="d-flex justify-content-around">
   <%= render 'shared/card', title: "London", text: "Find your beautiful flat in London", url: "https://images.unsplash.com/photo-1505761671935-60b3a7427bad?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" %>
   <%= render 'shared/card', title: "New York", text: "Find your beautiful flat in New York", url: "https://images.unsplash.com/photo-1522083165195-3424ed129620?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" %>
   <%= render 'shared/card', title: "Los Angeles", text: "Find your beautiful flat in Los Angeles", url: "https://images.unsplash.com/photo-1523595857-fe9ee689f76f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" %>
  </div>
</div>


<div class ="container">
  <div class="d-flex justify-content-around">
   <%= render 'shared/card', title: "Miami", text: "Find your beautiful flat in Miami", url: "https://images.unsplash.com/photo-1506966953602-c20cc11f75e3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" %>
   <%= render 'shared/card', title: "Berlin", text: "Find your beautiful flat in Berlin", url: "https://images.unsplash.com/photo-1560930950-5cc20e80e392?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" %>
   <%= render 'shared/card', title: "Munich", text: "Find your beautiful flat in Munich", url: "https://images.unsplash.com/photo-1554222413-74348b32d66e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="sticky-top">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://cdn.worldvectorlogo.com/logos/airbnb-2.svg" %>
      <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%= simple_form_for :search, url: flats_path, method: "GET", html: { class: 'form-inline' } do |f| %>
    <form class="form-inline">
        <%= f.input :location, label: false, input_html: {value: "" }, placeholder: "Location", class: "form-control mr-sm-2" %>
        <%= f.input :check_in, as: :date, html5: true, label: false %>
        <%= f.input :check_out, as: :date, html5: true, label: false %>
        <%= f.input :capacity, input_html: { class: "recognitionStyling form-control mr-sm-2" }, prompt: "Guests", collection: (1..5), label: false %>
        <%= f.submit "Search", class: 'btn btn-outline-success my-2 my-sm-0'%>
        <%end%>
    </form>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/RicardoLuisAraujo", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>